pull_request_rules:
- actions:
    comment:
      message: repository name full (wrong)
  conditions:
  - repository-name-short!=mergifyio-testing/functional-testing-repo-ErwanSimonetti
  name: no-draft
