pull_request_rules:
- actions:
    update:
      bot_account: mergify-test2
  conditions:
  - base=20220501011451/test_update_action_with_bot/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20220501011451/test_update_action_with_bot/main
  - label=merge
  name: merge
