pull_request_rules:
- actions:
    update:
      bot_account: mergify-test[bot]
  conditions:
  - base=20220501135819/test_update_action_with_bot/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20220501135819/test_update_action_with_bot/main
  - label=merge
  name: merge
