pull_request_rules:
- actions:
    comment:
      message: review-threads-unresolved comment
  conditions:
  - review-threads-unresolved="why are you still writing `foo` here ?"
  - review-threads-unresolved="foo"
  name: resolved-threads
