pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20211014143644/test_backport_merge_commit/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20211014143644/test_backport_merge_commit/stable/#3.1
  conditions:
  - base=20211014143644/test_backport_merge_commit/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
