pull_request_rules:
- actions:
    merge:
      strict: smart
  conditions:
  - base=20211014142147/test_merge_failure_smart_strict/main
  - status-success=continuous-integration/fake-ci
  name: strict merge on main
