pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20220501140015/test_update_action_with_bot/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20220501140015/test_update_action_with_bot/main
  - label=merge
  name: merge
